name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Create tag
      run: echo "tag=1.0" >> "$GITHUB_ENV"
    - name: Build and push the Docker image
      run: |
        docker login -u amitcarmi -p ${{ secrets.DOCKERHUB_LOGIN }}
        docker build . --file Dockerfile --tag philipjs:$tag
        docker tag philipjs:$tag amitcarmi/philipjs
        docker push amitcarmi/philipjs
